apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: depl
  name: depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: depl
    spec:
      containers:
      - image: rohit44docker/spring:v1.0
        name: spring
        resources: {}
status: {}
