apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: depl  # This should match the label in the deployment
  ports:
    - protocol: TCP
      port: 80            # Port exposed on the service (accessible from inside the cluster)
      targetPort: 8080     # Port in the container (the app's port)
      nodePort: 30001      # Port exposed on the nodes (accessible externally)
  type: NodePort          # This makes the service a NodePort type

